version: "2"

run:
  timeout: 5m

linters:
  default: none
  enable:
    - bodyclose

formatters:
  enable:
    - gofmt
    - goimports

  settings:
    gofmt:
      simplify: true

issues:
  max-issues-per-linter: 50
  max-same-issues: 10
