name: Dependabot rebase open PRs on main update

on:
  push:
    branches: [main]

permissions:
  contents: read
  issues: write
  pull-requests: read

jobs:
  request-dependabot-rebases:
    name: Request open Dependabot PR rebases
    uses: ./.github/workflows/request-dependabot-rebases.yaml
    permissions:
      contents: read
      issues: write
      pull-requests: read
